Adapt w.r.t. coq/coq#16004.
mit-plv/engine-bench pull request #6
Opened 2022-08-08 16:35 UTC by ppedrot

I've done this one by hand because it's really small. @JasonGross I am unsure of the amount of backwards compatibility you want to preserve, but the only two problematic attributes are the ones for the `Hint Rewrite` commands. Not sure if you want to add a script to simply remove them on old versions, or do something more clever.

2022-08-12 14:03 UTC, JasonGross commented
The CI only tests master and 8.11, so let's just add unsupported-attributes to
https://github.com/mit-plv/engine-bench/blob/d2cf8602d479b627c1f5d3d03044e8570af827ea/coq/PerformanceExperiments/Makefile#L28
and
https://github.com/mit-plv/engine-bench/blob/d2cf8602d479b627c1f5d3d03044e8570af827ea/coq/PerformanceDemos/Makefile#L19

2022-08-12 14:12 UTC, ppedrot commented
@JasonGross Done.

2022-08-17 14:53 UTC, ppedrot commented
@JasonGross ping. This is the last dev whose overlay is missing for coq/coq#16004.

2022-08-22 17:54 UTC, ppedrot commented
@JasonGross pingy-ping.

2022-08-22 18:00 UTC, JasonGross commented
Sorry, currently busy traveling.  I hope to get to this by the end of the week.  I think I need to switch the dev action to a docker container?  I'm not fully sure what's going wrong

2022-08-22 18:03 UTC, JasonGross commented
Ah, no, I think I figured it out.  Try rebasing on master now

2022-08-22 18:26 UTC, JasonGross requested changes

2022-08-22 18:26 UTC, JasonGross commented on coq/PerformanceDemos/Makefile
> +WARNINGS:=-notation-overridden,-unsupported-attributes
You need to `make update-_CoqProject` to get this change propagated to the checked-in _CoqProject

2022-08-22 19:23 UTC, merged